-- SQL Retail Sales Analysis - P1
CREATE DATABASE sql_project_p1;


-- Create TABLE
DROP TABLE IF EXISTS retail_sales;
CREATE TABLE retail_sales
            (
                transaction_id INT PRIMARY KEY,	
                sale_date DATE,	 
                sale_time TIME,	
                customer_id	INT,
                gender VARCHAR(15),
                age	INT,
                category VARCHAR(15),	
                quantity INT,
                price_per_unit FLOAT,	
                cogs FLOAT,
                total_sale FLOAT
            );


SELECT * FROM retail_sales

SELECT COUNT(*) FROM retail_sales

--Data Cleaning

SELECT * FROM retail_sales
WHERE 
    transaction_id IS NULL
    OR
    sale_date IS NULL
    OR 
    sale_time IS NULL
    OR
    gender IS NULL
    OR
    category IS NULL
    OR
    quantity IS NULL
    OR
    cogs IS NULL
    OR
    total_sale IS NULL;

--
DELETE FROM retail_sales
WHERE 
    transaction_id IS NULL
    OR
    sale_date IS NULL
    OR 
    sale_time IS NULL
    OR
    gender IS NULL
    OR
    category IS NULL
    OR
    quantity IS NULL
    OR
    cogs IS NULL
    OR
    total_sale IS NULL;

--Data Exploration

--How many sales we have?

SELECT COUNT(*) AS total_sale FROM retail_sales

--How many customers we have?

SELECT COUNT(DISTINCT customer_id) AS total_cus_id FROM retail_sales

--How many categories we have?

SELECT COUNT(DISTINCT category) AS total_cat FROM retail_sales

SELECT DISTINCT category FROM retail_sales

--Data Analysis and Business key Problems and Answers

--My Analysis and Findings

--Q.1 Write a SQL query to find the total revenue generated by the business
--Q.2 Write a SQL query to find which product categories generate the highest revenue
--Q.3 Write a SQL query to find total profit generated by the company
--Q.4 Write a SQL query to find the top 5 highest spending customers
--Q.5 Write a SQL query to retrieve all columns for sales made on '2022-11-05
--Q.6 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022
--Q.7 Write a SQL query to calculate the total sales (total_sale) for each category.
--Q.8 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.
--Q.9 Write a SQL query to find all transactions where the total_sale is greater than 1000.
--Q.10 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
--Q.11 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year
--Q.12 Write a SQL query to find the top 5 customers based on the highest total sales 
--Q.13 Write a SQL query to find the number of unique customers who purchased items from each category.
--Q.14 Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17)
--Q.15 Write a SQL query to find how does revenue vary month-wise
--Q.16 Write a SQL query to find difference in revenue contribution between male and female customers
--Q.17 Write a SQL query to find which age group generates the highest revenue
--Q.18 Write a SQL query to find which category has the highest total quantity sold
--Q.19 Write a SQL query to find what is the average spending per transaction
--Q.20 Write a SQL query to find transactions where cost exceeded revenue




--Q.1 Write a SQL query to find the total revenue generated by the business

SELECT SUM(total_sale) AS total_revenue
FROM retail_sales;

--Q.2 Write a SQL query to find which product categories generate the highest revenue

SELECT category,
       SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;

--Q.3 Write a SQL query to find total profit generated by the company

SELECT SUM(total_sale-COGS) AS total_profit
FROM retail_sales;

--Q.4 Write a SQL query to find the top 5 highest spending customers

SELECT customer_id,
       SUM(total_sale) as total_spent
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 5;

--Q.5 Write a SQL query to retrieve all columns for sales made on '2022-11-05

SELECT *
FROM retail_sales
WHERE sale_date = '2022-11-05';

--Q.6 Write a SQL query to retrieve all transactions where the category is 'Electronics' and the quantity sold is more than 2 in the month of Nov-2022

SELECT *
FROM retail_sales
WHERE 
     category = 'Electronics'
	 AND
	 TO_CHAR(sale_date, 'YYYY-MM') = '2022-11'
	 AND
	 quantity > 2

--Q.7 Write a SQL query to calculate the total sales (total_sale) for each category.

SELECT category,
       SUM(total_sale) AS total_sales,
	   COUNT(*) AS total_orders
FROM retail_sales
GROUP BY 1

--Q.8 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.

SELECT 
    ROUND(AVG(age), 2) AS avg_age
FROM retail_sales
WHERE category = 'Beauty'

--Q.9  Write a SQL query to find all transactions where the total_sale is greater than 1000.

SELECT *
FROM retail_sales
WHERE total_sale > 1000

--Q.10 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.

SELECT 
     category,
	 gender,
	 COUNT(*) AS total_trans
FROM retail_sales
GROUP BY
      category,
	  gender
ORDER BY 1		  
	  
--Q.11 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year

SELECT 
      year,
	  month,
	  avg_sale
FROM
(
	SELECT 
	     EXTRACT(YEAR FROM sale_date) AS year,
		 EXTRACT(MONTH FROM sale_date) AS month,
		 AVG(total_sale) AS avg_sale,
		 RANK() OVER(PARTITION BY EXTRACT(YEAR FROM sale_date) ORDER BY AVG(total_sale) DESC) AS rank
	FROM retail_sales
	GROUP BY 1,2
) AS t1
WHERE rank = 1


--ORDER BY 1,3 DESC


--Q.12 Write a SQL query to find the top 5 customers based on the highest total sales 

SELECT 
     customer_id,
	 SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

--Q.13 Write a SQL query to find the number of unique customers who purchased items from each category.

SELECT
     category,
	 COUNT (DISTINCT customer_id) AS unique_cust
FROM retail_sales	 
GROUP BY category

--Q.14  Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17)

WITH hourly_sale
AS
(
SELECT *,
     CASE
	     WHEN EXTRACT(HOUR FROM sale_time) < 12 THEN 'Morning'
		 WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
		 ELSE 'Evening'
	 END AS shift	 
FROM retail_sales
)
SELECT 
     shift,
     COUNT(*) AS total_orders	
FROM hourly_sale
GROUP BY shift

--SELECT EXTRACT(HOUR FROM CURRENT_TIME)

--Q.15 Write a SQL query to find how does revenue vary month-wise

SELECT EXTRACT(MONTH FROM sale_date) AS month,
       SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY month
ORDER BY month

--Q.16  Write a SQL query to find difference in revenue contribution between male and female customers

SELECT gender,
       SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY gender

--Q.17 Write a SQL query to find which age group generates the highest revenue

SELECT age,
       SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY age
ORDER BY revenue DESC

--Q.18 Write a SQL query to find which category has the highest total quantity sold

SELECT category,
     SUM(quantity) AS total_quantity_sold
FROM retail_sales
GROUP BY category
ORDER BY total_quantity_sold DESC

--Q.19 Write a SQL query to find what is the average spending per transaction

SELECT ROUND(AVG(total_sale)) AS avg_transaction_value
FROM retail_sales

--Q.20 Write a SQL query to find transactions where cost exceeded revenue

SELECT *
FROM retail_sales
WHERE cogs > total_sale


--End of project

